---
title: "John Hopkins_Regression Models_20141207"
author: "Yan Zhizhi"
date: "Sunday, December 07, 2014"
output: html_document
---
vedio 01-02 some basic definition -- notation   
关于SSE, MSE, RMSE等
vedio 01-03 General least squares for linear equations
讲了最小二乘法，一元线性回归的斜率和截距的计算方法
vedio 01-04 Historical side note, Regression to Mediocrity

###check our calculations on Intercept and Slope
```{r, message=FALSE}
library(UsingR);data(galton)
x <- galton$child
y <- galton$parent
beta1 <- cor(y,x) * sd(y)/sd(x)
beta0 <- mean(y) - beta1 * mean(x)
rbind(c(beta0, beta1), coef(lm(y ~ x)))
```
###标准化后的父亲与儿子的身高，看相关关系
```{r}
data(father.son)
#normalize the data
y <- (father.son$sheight - mean(father.son$sheight)) / sd(father.son$sheight)
x <- (father.son$fheight - mean(father.son$fheight)) / sd(father.son$fheight)
rho <- cor(x,y)
myPlot <- function(x,y){
  plot(x,y, xlab = "Father's height, normalized",
       ylab = "Son's height, normalized",
       xlim = c(-3,3), ylim = c(-3, 3),
       bg = "lightblue", col = "black", cex = 1.1, pch = 21,
       frame = FALSE)
}
myPlot(x,y)
abline(0,1) #if there were perfect correlation
abline(0, rho, lwd = 2, col = "red") #father predicts son
abline(0, 1/rho, lwd = 2, col = "green") #son predicts father, son on vertical axis
abline(h = 0); abline(v = 0) #reference lines for no relationship

#用ggplot2画图 
library(ggplot2)
g = ggplot(data.frame(x, y), aes(x = x, y = y))
g = g + geom_point(size = 5, alpha = .2, colour = "black")
g = g + geom_point(size = 4, alpha = .2, colour = "red")
g = g + geom_vline(xintercept = 0)
g = g + geom_hline(yintercept = 0)
g = g + geom_abline(position = "identity")
g = g + geom_abline(intercept = 0, slope = rho, size = 2)
g = g + geom_abline(intercept = 0, slope = 1 / rho, size = 2)
g = g + xlab("Father's height, normalized")
g = g + ylab("Son's height, normalized")
g
```
